server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /qians-thinker
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:  application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    initialSize: 5
    minIdle: 5
    maxActivr: 20
    #配置连接等待超时时间
    maxWait: 60000
    #配置间隔多久进行一次检测

  redis:
    jedis:
      pool:
        max-idle: 8
    #空闲时关闭时限 0表示永不关闭
    timeout: 0

swagger:
  enable: true

